name: audio_service_example
description: Demonstrates how to use the audio_service plugin.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  audio_service:
    path: ../
  audio_session: ^0.1.6
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  path_provider: ^2.0.1
  rxdart: ^0.27.0
  video_player:
    git:
      url: https://github.com/surfstudio/plugins.git
      ref: surf-video-player-2
      path: packages/video_player/video_player

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true