name: audio_service_example
description: Demonstrates how to use the audio_service plugin.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  audio_session:
  just_audio:
  flutter_tts:
  # TODO: use normal video player dependency when pull request is merged
  # https://github.com/flutter/plugins/pull/4324
  video_player:
    git:
      url: https://github.com/surfstudio/plugins.git
      path: packages/video_player/video_player
  rxdart:
  path_provider:
  audio_service:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true