name: audio_service_example
description: Demonstrates how to use the audio_service plugin.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  audio_session: ^0.1.6+1
  just_audio: ^0.9.13
  flutter_tts: ^3.2.2
  # video player has conflict with packages above so
  # comment them and related code and uncomment this to use video_player_example
  # TODO use normal video player dependency when pull request is accepted(will add link soon)
#  video_player:
#    git:
#      url: https://github.com/surfstudio/plugins.git
#      ref: surf-video-player-2
#      path: packages/video_player/video_player
  rxdart: ^0.27.2
  path_provider: ^2.0.1
  audio_service:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true